version: '3.8'

services:
  user-service:
    build: ./User-Service
    container_name: UserService
    ports:
      - "8082:8082"
    depends_on:
      - product-service
    networks:
      - backend
  product-service:
    build: ./Product-Service
    container_name: ProductService
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge