on:
  push:
    branches: [ master ]
    paths:
      - 'Product-Service/**'
      - 'User-Service/**'

jobs:
  build_and_deploy_product:
#    if: contains(github.event.head_commit.modified, 'Product-Service/')
    if: contains(github.event.commits.modified[*], 'Product-Service/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Build microservice with Maven
        run: |
          cd Product-Service
          mvn clean package

  build_and_deploy_user:
    if: contains(github.event.head_commit.modified, 'User-Service/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Build microservice with Maven
        run: |
          cd User-Service
          mvn clean package