on:
  push:
    branches: [ master ]
    paths:
      - '*-Service/**'  # Trigger deployment for any microservice directory if changed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservice: ['User-Service', 'Product-Service']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Check if Product-Service has changes
        id: product_service_check
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'Product-Service/**')
          echo "Changed files: $CHANGED_FILES"
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No changes detected in Product-Service"
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "Changes detected in Product-Service"
            echo "skip=false" >> $GITHUB_ENV
          fi
      - name: Build microservice with Maven
        run: cd ${{ matrix.microservice }} && mvn clean install -DskipTests