on:
  push:
    branches: [ master ]
    paths:
      - '*-Service-*/**'  # Trigger deployment for any microservice directory if changed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservice: ['User-Service', 'Product-Service']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Build microservice with Maven
        run: cd ${{ matrix.microservice }} && mvn clean install -DskipTests