on:
  push:
    branches: [ master ]
    paths:
      - User-Service/**
      - Product-Service/**


jobs:
  build_and_deploy:
    if: contains(github.event.head_commit.modified, '*/Product-Service/*')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Build microservice with Maven
        run: |
          cd Product-Service
          mvn clean package